name: as3438_exo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - transitleastsquares
      - radvel
  - numpy=1.24.3
  - scipy
  - scikit-learn
  - pandas
  - gpy
  - tqdm
#  - lightkurve=2.4.*
  - plotly
  - jupyter
  - matplotlib
  - ruff
  - emcee
  - corner
  - pre-commit
  - celerite
  - h5py
#  - george
