name: as3438_exo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - tqdm
  - lightkurve=2.4.*
  - scipy
  - plotly
  - jupyter
  - matplotlib
  - ruff
  - pre-commit
  - pip
  - celerite
  - h5py
  - dynesty
  - pip:
    - transitleastsquares
    - radvel
