name: as3438_exo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy==1.26.*
  - pandas==2.2.*
  - tqdm==4.66.*
  - lightkurve=2.4.*
  - scipy=1.13.*
  - plotly
  - jupyter
  - matplotlib
  - ruff
  - pre-commit
  - pip
  - pip:
    - transitleastsquares
